[package]
name = "kvs"
version = "0.1.0"
authors = ["Jackey Hua <jackeyhuasjtu@gmail.com>"]
description = "A simple key-value store"
edition = "2024"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
